service: your-little-earth-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: app/controllers/users.hello
    events:
     - http:
         path: users/create
         method: get

plugins:
  - serverless-offline
